base_model: /app/base_models/Meta-Llama-3-8B
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
tokenizer_use_fast: false

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: /app/data/data.jsonl
    type: sharegpt
    val_set_size: 0.1  # Use 10% of the data for validation
    conversation: chatml

chat_template: chatml

adapter: qlora
lora_model_dir:
lora_r: 128
lora_alpha: 256
lora_dropout: 0.05
lora_targets:
  - q
  - k
  - v
  - o
lora_target_linear: true
lora_fan_in_fan_out:
lora_modules_to_save:
  - embed_tokens
  - lm_head

dataset_prepared_path: /app/preprocess_datasets/
output_dir: /app/output

sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 3
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 2e-4

wandb_project: AI_Train
wandb_watch:
wandb_run_id:
wandb_log_model:

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
s2_attention:

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<|begin_of_text|>"
  eos_token: "<|im_end|>"
  pad_token: "<|end_of_text|>"
tokens:
  - "<|begin_of_text|>"
  - "<|im_start|>"
  - "<|im_end|>"
  - "<|end_of_text|>"
  - "<|INST|>"
  - "<|/INST|>"
  - "<|user|>"
  - "<|assistant|>"
  - "<|system|>"