model:
  name_or_path: /app/base_models/Meta-Llama-3-8B-Instruct
  load_in_8bit: true

data:
  train_file: /app/data/mira_data.json
  validation_file: /app/data/mira_data_eval_set.json

training:
  output_dir: /app/results
  num_train_epochs: 3
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  learning_rate: 2e-5
  weight_decay: 0.01
  evaluation_strategy: "epoch"
  fp16: true
  save_steps: 10_000
  save_total_limit: 2
  logging_dir: /app/logs
