base_model: /app/base_models/Meta-Llama-3-8B-Instruct
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
tokenizer_use_fast: false

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: /app/data/data.jsonl
    type: sharegpt
    conversation: chatml

chat_template: chatml

adapter: lora
lora_model_dir:
lora_r: 512
lora_alpha: 256
lora_dropout: 0.05
lora_targets:  # Define specific targets
  - qkv
  - qkv-o
  - qkv-down
  - qv
lora_target_linear: true
lora_fan_in_fan_out:

dataset_prepared_path: /app/preprocess_datasets/
output_dir: /app/output

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

gradient_accumulation_steps: 1
micro_batch_size: 3
num_epochs: 4
logging_steps: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 2e-5

wandb_project: AI_Train
wandb_watch:
wandb_run_id:
wandb_log_model:

train_on_inputs: false
group_by_length: false
bf16: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
local_rank:
xformers_attention: false
flash_attention: true
saves_per_epoch: 4
save_total_limit: 2
save_steps:
evals_per_epoch: 4
eval_sample_packing: false
debug:
deepspeed:
weight_decay: 0.05
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<|begin_of_text|>"
  eos_token: "<|eot_id|>"
  pad_token: "<|eot_id|>"
tokens:
  - "<|begin_of_text|>"
  - "<|eot_id|>"
  - "<|eot_id|>"