version: '3.8'

services:
  app:
    build: .
    ports:
      - "2212:2212"
      - "6006:6006"
    volumes:
      - .:/app
      - /mnt/user/appdata/AI_Trainer:/app
    environment:
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
      - TORCH_CUDA_ARCH_LIST=8.9 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
    shm_size: '16g'  # Increase shared memory size to 16GB